  
spring:
  application:
    name: stream-receiver
  # group
  ## spring.cloud.stream.bindings.[channelName].group = XXX
  cloud:
    stream:
      bindings:
        input: # channelName
          group: groupA
      # e.g., 'kafka', 'rabbit'
      default-binder: kafka
  rabbitmq:
    host: localhost
    password: 123
    port: 5672
    username: admin
  kafka: 
    bootstrap-servers:
     - localhost:9092