  
spring:
  application:
    name: stream-receiver
  cloud:
    stream:
      # e.g., 'kafka', 'rabbit'
      default-binder: kafka
  rabbitmq:
    host: localhost
    password: 123
    port: 5672
    username: admin
  kafka: 
    bootstrap-servers:
     - localhost:9092