server: 
  port: 9411

zipkin: 
  collector: 
    http:
      # Set to false to disable creation of spans via HTTP collector API
      enabled: true
  storage:
    type: mem
    mem:
      # Maximum number of spans to keep in memory.  When exceeded, oldest traces (and their spans) will be purged.
      # A safe estimate is 1K of memory per span (each span with 2 annotations + 1 binary annotation), plus
      # 100 MB for a safety buffer.  You'll need to verify in your own environment.
      # Experimentally, it works with: max-spans of 500000 with JRE argument -Xmx600m.
      max-spans: 500000
  
spring: 
  profiles: 
    active: shared

