  
spring:
  application:
    name: api-gateway-zuul
  # Spring Cloud Bus, Zipkin（Kafka, RabbitMQ）
  cloud:
    stream:
      # e.g., 'kafka', 'rabbit'
      default-binder: kafka
  kafka: 
    bootstrap-servers:
     - localhost:9092
  rabbitmq:
    host: localhost
    password: 123
    port: 5672
    username: admin
  # zipkin HTTP 收集
  zipkin: 
    baseUrl: http://127.0.0.1:9411
    sender:
      type: web
  # zipkin Kafka 收集
#  zipkin:
#    sender:
#      type: kafka
  # Sleuth  
  sleuth: 
    sampler: 
      probability: 1.0 # 采样率，默认为 0.1。1.0 为完全收集，收集比例越大，收集发送服务对服务器影响越大，同时对存储压力也很大。


# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123@localhost:8701/eureka
#      defaultZone: http://admin:123@host1:8701/eureka/,http://admin:123@host2:8702/eureka/,http://admin:123@host3:8703/eureka/


# Ribbon
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
  # Retry
  MaxAutoRetries: 2 
  MaxAutoRetriesNextServer: 0

# <service-id>.ribbon
users-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
  ConnectTimeout: 1000
  ReadTimeout: 3000
  MaxTotalHttpConnections: 500
  MaxConnectionsPerHost: 100
#  listOfServers: http://example1.com,http://example2.com
    
# Zuul    
zuul:
  # Ignored
#  ignored-services: users-provider
#  ignored-patterns: /**/hello/**

  # Disable filter
  ## zuul.<filter-name>.<filter-type>.disable=true
  AuthFilter:
    pre:
      disable: true 

  # Global Sensitive Headers
  sensitiveHeaders: '' 
#  sensitiveHeaders: Cookie,Set-Cookie,Authorization

  # Routes
#  routes:
    # <service-id> ReMapping
#    users-provider:
#      path: /usersProvider/**
#      serviceId: users-provider
#      sensitiveHeaders: ''  # Service sensitive headers
     # Single Mapping
#    test:
#      path: /test/**
#      url: http://127.0.0.1:8800

  add-host-header: true # Redirect Add Host
  forceOriginalQueryStringEncoding: true # Query String Encoding
  host:
    # Optimization
    maxPerRouteConnections: 20
    maxTotalConnections : 200
  retryable: true

# Error
error:
  path: /error