
spring:
  application:
    name: users-consumer-resttemplate
  # Spring Cloud Bus, Zipkin（Kafka, RabbitMQ）
  cloud:
    stream:
      # e.g., 'kafka', 'rabbit'
      default-binder: kafka
  kafka: 
    bootstrap-servers:
     - localhost:9092
  rabbitmq:
    host: localhost
    password: 123
    port: 5672
    username: admin
  # zipkin HTTP 收集
  zipkin: 
    baseUrl: http://127.0.0.1:9411
    sender:
      type: web
  # zipkin Kafka 收集
#  zipkin:
#    sender:
#      type: kafka
  # Sleuth  
  sleuth: 
    sampler: 
      probability: 1.0 # 采样率，默认为 0.1。1.0 为完全收集，收集比例越大，收集发送服务对服务器影响越大，同时对存储压力也很大。
    
# Eureka
eureka:
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 30
    serviceUrl:
      defaultZone: http://admin:123@localhost:8701/eureka
#      defaultZone: http://admin:123@host1:8701/eureka/,http://admin:123@host2:8702/eureka/,http://admin:123@host3:8703/eureka/
  instance:
    metadataMap:
      cluster: C1 # Turbine aggregator cluster name
      
feign:
  hystrix:
    enabled: true

# Ribbon
users-provider: # <serviceApplicationName>
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.BestAvailableRule
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule

    
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,health,info,refresh
#        include: *

# Error
error:
  path: /error